import { StyleSheet, Platform } from 'react-native';
import { colors, spacing, typography } from '../../../styles/global';

export const styles = StyleSheet.create({
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        justifyContent: 'flex-end',
        zIndex: 1,
    },
    modalContainer: {
        backgroundColor: colors.white,
        borderTopLeftRadius: 25,
        borderTopRightRadius: 25,
        height: '95%',
        shadowColor: colors.dark,
        shadowOffset: { width: 0, height: -4 },
        shadowOpacity: 0.2,
        shadowRadius: 12,
        elevation: 15,
    },
    modalHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: spacing.lg,
        borderBottomWidth: 1,
        borderBottomColor: '#e0e0e0',
    },
    headerContent: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: spacing.sm,
    },
    modalTitle: {
        ...typography.title,
        fontSize: 20,
        color: colors.dark,
        fontWeight: 'bold',
    },
    closeButton: {
        padding: spacing.xs,
    },
    modalContent: {
        flex: 1,
    },
    scrollContent: {
        padding: spacing.lg,
        paddingBottom: spacing.xl,
    },
    sectionTitle: {
        ...typography.h3,
        fontSize: 18,
        color: colors.primary,
        fontWeight: '700',
        marginTop: spacing.lg,
        marginBottom: spacing.md,
        paddingBottom: spacing.xs,
        borderBottomWidth: 2,
        borderBottomColor: colors.primary,
    },
    inputGroup: {
        marginBottom: spacing.lg,
    },
    label: {
        ...typography.body,
        fontSize: 15,
        color: colors.dark,
        fontWeight: '600',
        marginBottom: spacing.sm,
    },
    required: {
        color: '#ef4444',
    },
    inputContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#f8f9fa',
        borderRadius: 12,
        paddingHorizontal: spacing.md,
        paddingVertical: spacing.sm,
        borderWidth: 1,
        borderColor: '#e0e0e0',
        gap: spacing.sm,
    },
    input: {
        flex: 1,
        ...typography.body,
        fontSize: 15,
        color: colors.dark,
        paddingVertical: spacing.xs,
    },
    dateText: {
        flex: 1,
        ...typography.body,
        fontSize: 15,
        color: colors.dark,
        paddingVertical: spacing.xs,
    },
    datePickerContainer: {
        backgroundColor: colors.white,
        borderRadius: 12,
        marginTop: spacing.sm,
        padding: spacing.md,
        borderWidth: 1,
        borderColor: '#e0e0e0',
        overflow: 'hidden',
    },
    datePickerCloseButton: {
        backgroundColor: colors.primary,
        paddingVertical: spacing.md,
        paddingHorizontal: spacing.lg,
        borderRadius: 12,
        alignItems: 'center',
        marginTop: spacing.md,
    },
    datePickerCloseText: {
        ...typography.body,
        color: colors.white,
        fontSize: 16,
        fontWeight: '600',
    },
    pickerContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#f8f9fa',
        borderRadius: 12,
        paddingHorizontal: Platform.OS === 'ios' ? 0 : spacing.md,
        borderWidth: 1,
        borderColor: '#e0e0e0',
        gap: spacing.sm,
        overflow: 'hidden',
        ...Platform.select({
            ios: {
                height: 180,
                justifyContent: 'center',
            },
            android: {
                minHeight: 50,
            },
        }),
    },
    picker: {
        flex: 1,
        color: colors.dark,
        ...Platform.select({
            ios: {
                height: 180,
                marginVertical: -40,
            },
            android: {
                height: 50,
            },
        }),
    },
    pickerItem: {
        fontSize: 16,
        height: 180,
        color: colors.dark,
    },
    textAreaContainer: {
        alignItems: 'flex-start',
        minHeight: 100,
    },
    textAreaIcon: {
        marginTop: spacing.sm,
    },
    textArea: {
        minHeight: 80,
        paddingTop: spacing.sm,
    },
    hint: {
        ...typography.caption,
        fontSize: 12,
        color: colors.gray,
        marginTop: 4,
        marginLeft: spacing.xs,
    },
    modalFooter: {
        flexDirection: 'row',
        padding: spacing.lg,
        borderTopWidth: 1,
        borderTopColor: '#e0e0e0',
        gap: spacing.md,
        backgroundColor: colors.white,
    },
    cancelButton: {
        flex: 1,
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: spacing.md,
        borderRadius: 12,
        backgroundColor: colors.light,
        borderWidth: 1,
        borderColor: '#e0e0e0',
    },
    cancelButtonText: {
        ...typography.body,
        color: colors.dark,
        fontWeight: '600',
        fontSize: 16,
    },
    saveButton: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: spacing.md,
        borderRadius: 12,
        backgroundColor: colors.primary,
        gap: spacing.sm,
        shadowColor: colors.primary,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
        elevation: 6,
    },
    saveButtonText: {
        ...typography.body,
        color: colors.white,
        fontWeight: '700',
        fontSize: 16,
    },
});
