import { StyleSheet } from 'react-native';
import { colors, spacing, typography } from '../../../styles/global';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: colors.light,
    },
    header: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: spacing.md,
        paddingVertical: spacing.md,
        backgroundColor: colors.white,
        borderBottomWidth: 1,
        borderBottomColor: '#e0e0e0',
    },
    removeButton: {
        backgroundColor: colors.red,
    },
    backButton: {
        padding: spacing.sm,
        borderRadius: 20,
    },
    headerTitle: {
        ...typography.subtitle,
        fontSize: 18,
        color: colors.dark,
        fontWeight: '600',
    },
    editButton: {
        padding: spacing.sm,
        borderRadius: 20,
    },
    content: {
        flex: 1,
    },
    scrollContent: {
        padding: spacing.md,
        paddingBottom: 100,
    },
    mainCard: {
        backgroundColor: colors.white,
        borderRadius: 20,
        padding: spacing.lg,
        marginBottom: spacing.md,
        shadowColor: colors.dark,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.1,
        shadowRadius: 12,
        elevation: 5,
    },
    iconHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: spacing.lg,
    },
    iconContainer: {
        width: 70,
        height: 70,
        borderRadius: 35,
        backgroundColor: colors.primary,
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: spacing.md,
    },
    titleContainer: {
        flex: 1,
    },
    matchName: {
        ...typography.title,
        fontSize: 22,
        color: colors.dark,
        fontWeight: 'bold',
        marginBottom: spacing.sm,
    },
    statusBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: spacing.md,
        paddingVertical: spacing.xs,
        borderRadius: 20,
        alignSelf: 'flex-start',
        gap: 6,
    },
    statusText: {
        ...typography.caption,
        fontSize: 13,
        fontWeight: '600',
    },
    infoSection: {
        gap: spacing.md,
    },
    infoCard: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#f8f9fa',
        padding: spacing.md,
        borderRadius: 12,
        gap: spacing.md,
    },
    infoContent: {
        flex: 1,
    },
    infoLabel: {
        ...typography.caption,
        fontSize: 12,
        color: colors.gray,
        marginBottom: 4,
    },
    infoValue: {
        ...typography.body,
        fontSize: 15,
        color: colors.dark,
        fontWeight: '600',
    },
    section: {
        backgroundColor: colors.white,
        borderRadius: 20,
        padding: spacing.lg,
        marginBottom: spacing.md,
        shadowColor: colors.dark,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.08,
        shadowRadius: 8,
        elevation: 3,
    },
    sectionHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: spacing.md,
        gap: spacing.sm,
    },
    sectionTitle: {
        ...typography.subtitle,
        fontSize: 18,
        color: colors.dark,
        fontWeight: '600',
    },
    playersProgress: {
        marginBottom: spacing.md,
    },
    progressBar: {
        height: 10,
        backgroundColor: '#e0e0e0',
        borderRadius: 5,
        overflow: 'hidden',
        marginBottom: spacing.sm,
    },
    progressFill: {
        height: '100%',
        backgroundColor: colors.primary,
        borderRadius: 5,
    },
    progressText: {
        ...typography.caption,
        fontSize: 14,
        color: colors.dark,
        fontWeight: '600',
        textAlign: 'center',
    },
    playersList: {
        gap: spacing.sm,
    },
    playerCard: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#f8f9fa',
        padding: spacing.md,
        borderRadius: 12,
        gap: spacing.md,
    },
    playerAvatar: {
        width: 48,
        height: 48,
        borderRadius: 24,
        backgroundColor: colors.primary,
        justifyContent: 'center',
        alignItems: 'center',
    },
    playerInfo: {
        flex: 1,
    },
    playerName: {
        ...typography.body,
        fontSize: 15,
        color: colors.dark,
        fontWeight: '600',
        marginBottom: 2,
    },
    playerLevel: {
        ...typography.caption,
        fontSize: 12,
        color: colors.gray,
    },
    organizerBadge: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#fff3e0',
        paddingHorizontal: spacing.sm,
        paddingVertical: 4,
        borderRadius: 12,
        gap: 4,
    },
    organizerText: {
        ...typography.caption,
        fontSize: 11,
        color: colors.orange,
        fontWeight: '600',
    },
    emptyPlayers: {
        alignItems: 'center',
        paddingVertical: spacing.xl,
    },
    emptyText: {
        ...typography.body,
        color: colors.gray,
        marginTop: spacing.sm,
    },
    description: {
        ...typography.body,
        fontSize: 15,
        color: colors.dark,
        lineHeight: 22,
    },
    additionalInfo: {
        gap: spacing.md,
    },
    infoRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingVertical: spacing.sm,
        borderBottomWidth: 1,
        borderBottomColor: '#f0f0f0',
    },
    infoRowLabel: {
        ...typography.body,
        fontSize: 15,
        color: colors.gray,
    },
    infoRowValue: {
        ...typography.body,
        fontSize: 15,
        color: colors.dark,
        fontWeight: '600',
    },
    actionButtons: {
        position: 'absolute',
        bottom: 0,
        left: 0,
        right: 0,
        flexDirection: 'row',
        backgroundColor: colors.white,
        padding: spacing.md,
        borderTopWidth: 1,
        borderTopColor: '#e0e0e0',
        gap: spacing.md,
        shadowColor: colors.dark,
        shadowOffset: { width: 0, height: -2 },
        shadowOpacity: 0.1,
        shadowRadius: 8,
        elevation: 10,
    },
    shareButton: {
        width: 56,
        height: 56,
        borderRadius: 28,
        backgroundColor: colors.light,
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 2,
        borderColor: colors.primary,
    },
    joinButton: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: colors.primary,
        height: 46,
        borderRadius: 28,
        gap: spacing.sm,
        shadowColor: colors.primary,
        shadowOffset: { width: 0, height: 3 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
        elevation: 6,
    },
    joinButtonText: {
        ...typography.body,
        color: colors.white,
        fontWeight: '700',
        fontSize: 16,
    },
    fullButton: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: colors.gray,
        height: 56,
        borderRadius: 28,
        gap: spacing.sm,
    },
    fullButtonText: {
        ...typography.body,
        color: colors.white,
        fontWeight: '700',
        fontSize: 16,
    },
});
